name: one_clock
version: 1.0.1
description: "Flutter analog and digital clock plugin"
homepage: https://github.dev/AurangzebHusain/one_clock

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
