name: one_clock
version: 1.0.1
description: "This package can be used to build a digital as well as analog clock. Written on the top of analog_clock package."
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
